### ISSUE TITLE
Latest changes after 0.3.2 breaking code while running a post request.

### ISSUE THREAD

**Issue by prabhu-das** [govdelivery/infoblox#32] opened 2015-06-18 15:47 UTC
After creating a record object 
record = Infoblox::Host.new(connection: connection, ipv4addrs: params[:ipv4addrs], name: params[:name])

It throws the below error when I do 
record.post
ERROR: undefined method `remote_attribute_hash' for
{:ipv4addr=>"10.10.70.12", :mac=>nil}:Hash

It works if I revert to version 0.3.2. I guess something is breaking when the attr_readers/accessors are changed. Becoz I don't see any other major changes. 
@unclebilly Can you please have a look at it.

**Comment by Klaas-** [comment] 2015-06-18 17:57
I'd say thats a duplicate of my other bug report - but I'm not sure how to set this on github :D

**Comment by unclebilly** [comment] 2015-06-18 18:32
This is a duplicate of #31.  I'll have a fix shortly - it will be in v0.4.1.

**Closed by unclebilly** 2015-06-18 18:32 UTC
